### ISSUE TITLE
Error while running data script

### ISSUE THREAD

**Issue by amogh112** [ifp-uiuc/do-neural-networks-learn-faus-iccvw-2015#3]
I am trying to run the data script for CK+ dataset with python 2

> python make_ck_plus_dataset.py --input_path "E:\CK+" --save_path E:\approach1_april_10\data

It gives the following error:

> Traceback (most recent call last):
>   File "make_ck_plus_dataset.py", line 459, in <module>
>     numpy_file_generator.run()
>   File "make_ck_plus_dataset.py", line 298, in run
>     num_samples)
>   File "make_ck_plus_dataset.py", line 332, in make_data_label_mats
>     y[index_slice] = label_vec
> ValueError: could not broadcast input array from shape (4) into shape (3)

What am I doing wrong?

**Comment by pkhorrami4** [comment]
Hi. 

When you run the code what is in the CK+ folder? The CK+ folder should contain the following: 
```
CK_Agreement_Form.pdf
extended-cohn-kanade-images.zip
Consent-for-publication.doc
CVPR2010_CK.pdf
Emotion_labels.zip
FACS_labels.zip
ReadMeCohnKanadeDatabase_website.txt
```

I ran the code again and it was able to generate the dataset. I've included a copy of the conda environment I used as a zipped yaml file. You can try using it to set up your environment 
[environment.yml.zip](https://github.com/ifp-uiuc/do-neural-networks-learn-faus-iccvw-2015/files/1905530/environment.yml.zip). Hope this helps!

**Comment by amogh112** [comment]
Thanks
I was able to correct it, a system specific problem.
You can close the issue

**Comment by nikhileshva** [comment]
@amogh112 @pkhorrami4 
I am having the same problem. This is my folder structure. 


![screen shot 2018-04-27 at 10 32 47 pm](https://user-images.githubusercontent.com/9674911/39383829-01613ba4-4a6b-11e8-96c1-1af5f3feea5e.png)

And when I open cohn-kanade-images, there are subject folders. The same with Emotion_labels. 

Any help would be appreciated. 

Thanks

**Comment by amogh112** [comment]
hi 
it was probably happening because in one of the folder instead of 4, only 3 pictures were being cropped and saved. So it ran into indexing problem. You can see the folder by seeing where the error occurs. Try to correct it by manually adding one image for that folder(you could copy one of the images already in that folder), or change the python code where the error occurs, to ignore the error and move on to the next iteration of the loop.
Hope it helps

**Comment by nikhileshva** [comment]
@amogh112 It is happening inisde S506 folder. It has four folders then inside. 
Also, those four folders inside S506 have more than 10 images each.

**Comment by nikhileshva** [comment]
Would it affect the data that is generated if I ignore the error and move on to the next iteration?

**Comment by nikhileshva** [comment]
Also, those four folders inside S506 have more than 10 images each.

**Comment by amogh112** [comment]
The cropped images are being saved in cohn-kanade-images/S506/006, where instead of 4 only 3 images were saved. So I just made a copy of one of the images in it. Yeah, 5 folders were lost. You would have to see why images aren't being cropped and saved. Sorry, can't help you with that. Please share your solution if you end up doing it.

**Comment by NomiMalik0207** [comment]
@amogh112 i am facing this error can you help me ?
Condensed CK+ Dataset Statistics: 
Total Number of Image Sequences: 327
Total Number of Label Sequences: 327
Number of sequences with correponding label .txt file: 327
Total Number of Subjects: 118
Number of image files: 1307

Detecting and Cropping Faces
C:\Users\nomi\Anaconda3\lib\site-packages\skimage\transform\_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
Missed the face!
Missed the face!
Missed the face!
Missed the face!
Missed the face!
Traceback (most recent call last):
Missed Faces:  ['./CK_PLUS_HERE/cohn-kanade-images\\S010\\002\\S010_002_00000012.png', './CK_PLUS_HERE/cohn-kanade-images\\S010\\002\\S010_002_00000013.png', './CK_PLUS_HERE/cohn-kanade-images\\S010\\002\\S010_002_00000014.png', './CK_PLUS_HERE/cohn-kanade-images\\S042\\002\\S042_002_00000014.png', './CK_PLUS_HERE/cohn-kanade-images\\S076\\001\\S076_001_00000015.png']
  File "D:/Masters/Research/dexpression-master/make_ck_plus_dataset.py", line 455, in <module>
    face_cropper.run()
  File "D:/Masters/Research/dexpression-master/make_ck_plus_dataset.py", line 199, in run
    self.crop_and_align_all_faces(self.image_path)
  File "D:/Masters/Research/dexpression-master/make_ck_plus_dataset.py", line 227, in crop_and_align_all_faces
    self.write_list_to_file(missed_faces_file_path, missed_faces)
  File "D:/Masters/Research/dexpression-master/make_ck_plus_dataset.py", line 204, in write_list_to_file
    f.write(item + '\n')
TypeError: a bytes-like object is required, not 'str'
i am unable to generate .npy file of dataset due to this face crop error.

**Comment by Joyli66** [comment]
@amogh112 Thank you for your question. I encountered the same problem as you but I can't fix it. Could you please tell me how you correct it? I would really appreciate it! Thank you:)
